### ISSUE TITLE
Replace usage of `keyboard` module

### ISSUE THREAD

**Issue by iamDyeus** [iamDyeus/tkreload#1]
The library is currently detecting global keyboard inputs, but it should be limited to capturing inputs specifically within the terminal. Modifying the behavior to restrict input detection to terminal-only interactions

**Comment by INEcodes** [comment]
Can I get this issue assigned to me, as think I can solve this issue.
Thanks

BTW loved the project idea

**Comment by iamDyeus** [comment]
Go ahead, I'll assign the issue to you.

> BTW loved the project idea

Thanks! The goal is to create a tool that helps others boost their efficiency.

**Comment by iamDyeus** [comment]
7c795e186807ae5f9dfea30583a2b90a1d03a8c9
