### ISSUE TITLE
[BUG] Issue with PyPi in GitHub Actions

### ISSUE THREAD

**Issue by iamDyeus** [iamDyeus/tkreload#10]
**Describe the bug**
The `README.md` file is not being processed correctly according to `setup.py`, preventing it from displaying properly on the PyPi project page and causing the build to fail.

**To Reproduce**
 Refer to these [build logs](https://github.com/iamDyeus/tkreload/actions/runs/11464540473) for details.

**Expected behavior**
The build should complete without errors.

**Additional context**
This issue occurs only in the GitHub Actions workflow; the build works correctly when executed locally.

**Comment by iamDyeus** [comment]
For now, I manually uploaded the latest version using:
`twine upload dist/*`

**Comment by iamDyeus** [comment]
Also, It would be more better to manage all versions from a single file rather than updating them individually in multiple files.

**Comment by agronholm** [comment]
Why do you have a `setup.py` in the first place? You only need a `pyproject.toml`, as the package is pure Python.

**Comment by agronholm** [comment]
Also, your project does not have a file named `README.md`. It has a `README.MD`.

**Comment by iamDyeus** [comment]
> Also, your project does not have a file named `README.md`. It has a `README.MD`.

Sorry to be navie, Aren't those the same things?

**Comment by agronholm** [comment]
No, the file in your repository has an upper case suffix (`.MD`) while the expected file name has a lower case suffix (`.md`). These file names are not the same.

**Comment by iamDyeus** [comment]
> Why do you have a `setup.py` in the first place? You only need a `pyproject.toml`, as the package is pure Python.

If you could fix this, that would be great! (I'm quite new to publishing on PyPI.)

**Comment by agronholm** [comment]
Alright, I'll try to cook up something for you tonight.

**Comment by iamDyeus** [comment]
> No, the file in your repository has an upper case suffix (`.MD`) while the expected file name has a lower case suffix (`.md`). These file names are not the same.

Aah got it, so I was testing on windows OS and github actions run on linux, i.e case sensitive file names. 😅

**Comment by agronholm** [comment]
I've created https://github.com/iamDyeus/tkreload/pull/13 to overhaul a number of things here. You can pick and choose the things you like if you feel uncomfortable with some of the changes I made. Just let me know in the PR.
