### ISSUE TITLE
Need Logo Design

### ISSUE THREAD

**Issue by iamDyeus** [iamDyeus/tkreload#11]
I propose that we create a logo for our project that visually represents its purpose. I envision a design similar to the one shown below:

![image](https://github.com/user-attachments/assets/35c9ca48-dc83-4692-a19d-8b00d8c61e55)

For our logo, we could use the Tkinter logo as a base, with a refresh icon on top to symbolize functionality related to refreshing or reloading.

**Comment by Kabiirk** [comment]
Hi @iamDyeus ,

I can work on this please assign this to me, what assets do you require as an output of this task ? (for e.g. SVG, PNGs etc.) also let me know the dimensions in which you require these assets.

**Comment by iamDyeus** [comment]
@Kabiirk, Ideally, we need two files:

1. Main SVG logo – Similar in dimensions to the customtkinter example I shared earlier.
2. GitHub banner (PNG) – Please follow the GitHub [template](https://github.com/iamDyeus/tkreload/settings/og-template).

Once they're ready, you can open a PR by adding these files to the `.assets` folder in the root directory. Thanks!

**Comment by iamDyeus** [comment]
One suggestion could be to replace the plain white logo text with a white gradient text, which might work better, especially considering the light mode.

**Comment by Kabiirk** [comment]
Sure ! Let me work on it & share something

**Comment by Kabiirk** [comment]
Hi @iamDyeus ,

I have created 2 main logos with (1 extra variant for each).
My main thinking behind this design was to retain the blue 'O' of `Custom Tkinter` logo  as it looks like a loading icon. Moreover, I integrated the loading 'O' into the text itself for a sleeker look (I also love such typographic logos).



## Logo 1:
### Variant 1 (gradient cap)
![Logo 1 Variant 1](https://github.com/user-attachments/assets/33324eec-03a1-4641-b3ce-a7f41411333c)

### Variant 2 (solid cap)
![Logo 1 Variant 2](https://github.com/user-attachments/assets/f33516a9-10e3-4264-9348-6922fe3f2993)

## Logo 2:
### Variant 1 (gradient cap)
![Logo 2 Variant 1](https://github.com/user-attachments/assets/d0811cc7-2416-41d1-8491-3403fc8a8e7b)


### Variant 2 (solid cap)
![Logo 2 Variant 2](https://github.com/user-attachments/assets/c964f292-00ed-448f-88d3-30c9c6c20b4c)


Let me know which one you like.

**Comment by iamDyeus** [comment]
@Kabiirk Nice Work!
I think "Logo 2" looks good, you can move ahead with any of the variant you like.
