### ISSUE TITLE
Missing Dockerfile for containerization

### ISSUE THREAD

**Issue by kartik-212004** [iamDyeus/tkreload#17]
The project currently lacks a Dockerfile, which is essential for containerizing the application and ensuring smooth deployment across different environments. Adding a Dockerfile would help developers and users run the application in a consistent environment without needing to install dependencies manually.

**Comment by iamDyeus** [comment]
I don't really have an opinion on whether we should dockerize a simple Python module. Maybe @agronholm could give some suggestions, as he's the one who restructured the content in this repo.

**Comment by agronholm** [comment]
It's exceedingly rare for libraries to provide Dockerfiles. Why do you think it's needed here? Application developers would need to make their own Dockerfiles anyway.
