### ISSUE TITLE
Implement Tests

### ISSUE THREAD

**Issue by iamDyeus** [iamDyeus/tkreload#3]
Currently, there are no tests implemented for the library during the setup process. 

This issue aims to:
- Determine and implement the most suitable testing framework.
- Develop and integrate tests for the library to ensure its functionality and reliability.

**Comment by SpreadSheets600** [comment]
@iamDyeus I would be glad working on it 🙂

**Comment by iamDyeus** [comment]
Go ahead, I'll assign the issue to you.
Please make sure you update the documentation for running tests so that other members can contribute as well.
